version: '3.2'

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS:-password123}
    expose:
     - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    network_mode: host

volumes:
  redis-data:
  redis-conf:
